### PR TITLE
Adding Bootstrap JS and CSS files

### PR DESCRIPTION
**Pull request by lachieMiles**
Adding Bootstrap files (JS and CSS) to the project
When opening the new 'assetts folder', there should be a JavaScript file and a CSS file

### CODE REVIEW

**Comment by Hagustin** [comment]
Very nicely done mate!

**Review by brankad75 — CHANGES_REQUESTED** [review]
Please change name of the "Assetts" folder to "Assets"

**Review by brankad75 — APPROVED** [review]
Approved to commit

**Review by Ishan74 — APPROVED** [review]
excellent!!!

**Pull request merged**
